name: work-1
on:
  push:
    branches:
      - main
jobs:
  hello1:
    runs-on: ubuntu-latest
    steps:
    - name: sayHi
      run: echo "Hi"
    - name: Wait for 10 seconds
      run: sleep 10 #10 초 대기
    - name: sayMyName
      run: echo "{{ gihub.actor }}"
  hello2:
    runs-on: ubuntu-latest
    steps:
    - name: sayHi
      run: echo "Hi"
    - name: Wait for 10 seconds
      run: sleep 10 #10 초 대기
    - name: sayMyName
      run: echo "{{ gihub.actor }}"
